name = "magnet-search-api"
main = "worker.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "magnet-search-api"

[env.staging]
name = "magnet-search-api-staging"

[[env.production.d1_databases]]
binding = "DB"
database_name = "magnet-search-prod"
database_id = "your-d1-database-id"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "magnet-search-staging" 
database_id = "your-staging-d1-database-id"
