# Cloudflare Workers 配置文件

name = "magnet-search-backend"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 环境变量
[env.production.vars]
ENVIRONMENT = "production"

[env.development.vars]
ENVIRONMENT = "development"

# D1 数据库绑定
[[env.production.d1_databases]]
binding = "DB"
database_name = "magnet-search-db"
database_id = "your-database-id-here"

# Cloudflare Workers 配置文件

name = "magnet-search-backend"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 环境变量
[env.production.vars]
ENVIRONMENT = "production"

[env.development.vars]
ENVIRONMENT = "development"

# D1 数据库绑定
[[env.production.d1_databases]]
binding = "DB"
database_name = "magnet-search-db"
database_id = "your-database-id-here"

[[env.development.d1_databases]]
binding = "DB"
database_name = "magnet-search-db-dev"
database_id = "your-dev-database-id-here"

# 密钥配置（需要通过wrangler secret设置）
# wrangler secret put JWT_SECRET
# wrangler secret put ADMIN_PASSWORD

# KV 存储绑定（可选，用于高频缓存）
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# 速率限制配置
[limits]
cpu_ms = 50000

# 自定义域名配置（生产环境）
[env.production]
routes = [
  "api.your-domain.com/*"
]

# 开发环境配置
[env.development]
# 本地开发时的配置

# 构建配置
[build]
command = ""

# 部署前钩子
[triggers]
# 可以配置cron触发器来定期清理数据
# crons = ["0 2 * * *"] # 每天凌晨2点清理过期数据