export { authRoutes } from './auth';
export { userRoutes } from './user';
export { sourceRoutes } from './sources';
export { communityRoutes } from './community';
export { systemRoutes } from './system';
export { searchRoutes } from './search';
export { adminRoutes } from './admin';
export { configRoutes } from './config';
export { javRoutes } from './jav';
