// ==================================================================
// 共享验证规则 - 前后端通用
// 前后端都从本文件导入，保持规则一致性
// 改了需要前后端同步重新部署
// ==================================================================

export const VALIDATION_RULES = {

  USERNAME: {
    MIN_LENGTH: 3,
    MAX_LENGTH: 20,
  },
  PASSWORD: {
    MIN_LENGTH: 6,
    MAX_LENGTH: 100,
  },
  EMAIL: {
    MAX_LENGTH: 255,
  },

  KEYWORD: {
    MIN_LENGTH: 1,
    MAX_LENGTH: 200,
  },
  SEARCH_SOURCES: {
    MAX_COUNT: 50,
  },

  FAVORITES: {
    MAX_SYNC_COUNT: 1000,
    MAX_COUNT: 1000,
    TITLE_MAX_LENGTH: 100,
    SUBTITLE_MAX_LENGTH: 200,
    URL_MAX_LENGTH: 500,
    ICON_MAX_LENGTH: 50,
  },

  SEARCH_HISTORY: {
    MAX_COUNT: 1000,
  },

  MAJOR_CATEGORY: {
    NAME_MAX_LENGTH: 30,
    DESCRIPTION_MAX_LENGTH: 500,
    ICON_MAX_LENGTH: 10,
  },
  CATEGORY: {
    NAME_MAX_LENGTH: 50,
    DESCRIPTION_MAX_LENGTH: 500,
    ICON_MAX_LENGTH: 10,
  },

  SOURCE: {
    NAME_MAX_LENGTH: 100,
    SUBTITLE_MAX_LENGTH: 200,
    DESCRIPTION_MAX_LENGTH: 1000,
    URL_MAX_LENGTH: 500,
    ICON_MAX_LENGTH: 10,
  },

  USER_CONFIG: {
    CUSTOM_NAME_MAX_LENGTH: 100,
    CUSTOM_SUBTITLE_MAX_LENGTH: 200,
    CUSTOM_ICON_MAX_LENGTH: 50,
    NOTES_MAX_LENGTH: 500,
    BATCH_UPDATE_MAX_COUNT: 100,
  },

  TAG: {
    NAME_MIN_LENGTH: 2,
    NAME_MAX_LENGTH: 20,
    DESCRIPTION_MAX_LENGTH: 200,
    MAX_COUNT_PER_SOURCE: 10,
  },
  SHARED_SOURCE: {
    NAME_MIN_LENGTH: 2,
    NAME_MAX_LENGTH: 100,
    SUBTITLE_MAX_LENGTH: 200,
    DESCRIPTION_MAX_LENGTH: 2000,
    URL_MAX_LENGTH: 500,
  },
  REVIEW: {
    COMMENT_MAX_LENGTH: 1000,
  },
  REPORT: {
    REASON_MAX_LENGTH: 100,
    DETAILS_MAX_LENGTH: 1000,
  },

  PAGINATION: {
    DEFAULT_PAGE_SIZE: 20,
    MAX_PAGE_SIZE: 100,
    MAX_LOG_PAGE_SIZE: 200,
    DEFAULT_HISTORY_LIMIT: 50,
    MAX_HISTORY_LIMIT: 200,
  },

  SUGGESTIONS: {
    MIN_KEYWORD_LENGTH: 2,
    MAX_LIMIT: 20,
  },

  TRENDING: {
    DEFAULT_HOURS: 24,
    MAX_HOURS: 168,
    DEFAULT_LIMIT: 20,
    MAX_LIMIT: 50,
  },

  VERIFICATION_CODE: {
    LENGTH: 6,
    EXPIRY_MS: 15 * 60 * 1000,
    MAX_ATTEMPTS: 5,
    RESEND_INTERVAL_MS: 60 * 1000,
  },

  EMAIL_CHANGE: {
    REQUEST_EXPIRY_MS: 30 * 60 * 1000,
    PENDING_EXPIRY_MINUTES: 30,
  },

  SOURCE_CHECK: {
    MAX_BATCH_CHECK: 30,
    MAX_CACHE_QUERY: 50,
    DEFAULT_TIMEOUT_MS: 10000,
    BATCH_TIMEOUT_MS: 5000,
    CACHE_DURATION_MS: 5 * 60 * 1000,
    MAX_CONCURRENT_CHECKS: 3,
  },
} as const;