name = "codeseek-site"
main = "src/index.js"
compatibility_date = "2024-03-18"
workers_dev = true

[vars]
# 生产环境配置
ENVIRONMENT = "production"
DEBUG = "false"

# 允许直接浏览器访问
ALLOW_DIRECT_ACCESS = "true"

# 额外的代理目标白名单（可选，补充代码中的硬编码列表）
EXTRA_PROXY_TARGETS = ""

# 备用域名配置
BACKUP_DOMAINS = "backup1.omnibox.pp.ua,backup2.omnibox.pp.ua"

# 故障转移配置
ENABLE_FAILOVER = "true"
FAILOVER_TIMEOUT = "5000"